### ISSUE TITLE
edgeAgent throws an exception 

### ISSUE THREAD

**Issue by sagar-mallar** [Azure/iot-edge#426]
Hi ,

* The container which gets created on iotedgectl start is exiting well within a minute.

Edit 1 : docker logs -

2017-11-23 05:10:44 [FTL] - Fatal error starting edge agent.
System.TimeoutException: Operation timeout expired.
at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass79_0.<ApplyTimeout>b__2(Task t)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<Create>d__10.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Edge.Agent.Service.Modules.FileBackupConfigSourceModule.<>c.<<Load>b__7_4>d.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/FileBackupConfigSourceModule.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Edge.Agent.Service.Modules.FileBackupConfigSourceModule.<<Load>b__7_5>d.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/FileBackupConfigSourceModule.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.<MainAsync>d__4.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 110
2017-11-23 05:10:44 [INF] - Termination requested, closing.

===============================================

* on contrary i was able to run completely on a raspberry pi 3 but not on Windows 10 Pro fall creators update. 

Unfortunately there is no straight approach to create edge modules for ARM64 devices, kind of stuck.

**Comment by avranju** [comment]
Currently if all retries fail when connecting to IoT Hub the agent eventually quits. The retry policy could be be amended so that it attempts to recover the connection basically indefinitely with some type of back-off. Will look into this.

**Comment by myagley** [comment]
This is fixed in the latest version of the Edge Agent.
