### ISSUE TITLE
edgeHub module constantly restarting: Permission denied (generate-cert.sh)

### ISSUE THREAD

**Issue by SamVanhoutte** [Azure/iot-edge#432]
I am using Docker for Windows, with Linux containers and have set up the edge runtime, with the **--auto-cert-gen-force-no-passwords** flag.

When I am starting the edge runtime, I can see the following message in the edgeHub logs:

```
scripts/linux/start.sh: line 13: ./scripts/linux/generate-cert.sh: Permission denied

Unhandled Exception: System.AggregateException: One or more errors occurred. (error:2006D080:BIO routines:BIO_new_file:no such file) ---> Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file
   at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
   at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.<MainAsync>d__4.MoveNext() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 50
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 31
Aborted
```

**Comment by mrohera** [comment]
Hello SamVanhoutte,
Are you still experiencing this problem? As we discussed via another channel, it appears to have been an inconsistency in your setup and a clean reinstall has got you through. We cannot repro this problem. If you don't have any other comments, we can close this issue.

**Comment by SamVanhoutte** [comment]
Apologies for not updating the status.  The real root cause was not found, but could be related to one of the following issues:

- An earlier version of a private preview container
- The switching from Windows containers to Linux container
- Another (unknown) cause

It was solved by performing a 'factory reset' of my docker runtime.
