### ISSUE TITLE
Error when trying to install edge runtime on Ubuntu

### ISSUE THREAD

**Issue by murdockcrc** [Azure/iot-edge#435]
I am trying to run this command:
`sudo pip install -U azure-iot-edge-runtime-ctl`

And I get this error:
```
Downloading/unpacking azure-iot-edge-runtime-ctl
  Could not find a version that satisfies the requirement azure-iot-edge-runtime-ctl (from versions: 1.0.0rc14, 1.0.0rc11, 1.0.0rc14, 1.0.0rc13, 1.0.0rc11, 1.0.0rc13)
Cleaning up...
No distributions matching the version for azure-iot-edge-runtime-ctl
Storing debug log for failure in /home/murdockcrc/.pip/pip.log
```
Here's the content of pip.log
```
Downloading/unpacking azure-iot-edge-runtime-ctl
  Getting page https://pypi.python.org/simple/azure-iot-edge-runtime-ctl/
  URLs to search for versions for azure-iot-edge-runtime-ctl:
  * https://pypi.python.org/simple/azure-iot-edge-runtime-ctl/
  Analyzing links from page https://pypi.python.org/simple/azure-iot-edge-runtime-ctl/
    Found link https://pypi.python.org/packages/22/51/41c972427bb410521fc72772c59a140fe841f7c51edb45aefc44e2d202ad/azure_iot_edge_runtime_ctl-1.0.0rc14-py2.py$
    Found link https://pypi.python.org/packages/57/61/1716c5d31f5db0e66e02847ea288ee7b22053ae8dcbcb2b6720ddc41e4e4/azure_iot_edge_runtime_ctl-1.0.0rc11-py2.py$
    Found link https://pypi.python.org/packages/85/12/2de6ec3f9b99f70483531ebbcd81992cc0b0dec07cce64c4342094a31b67/azure-iot-edge-runtime-ctl-1.0.0rc14.tar.gz$
    Found link https://pypi.python.org/packages/9c/1f/900bb21d98a332083e3ff0ee2b34b3425f22677c32719ed77f9b9803c299/azure_iot_edge_runtime_ctl-1.0.0rc13-py2.py$
    Found link https://pypi.python.org/packages/d2/89/423440eb2576d0884e809cd9521a5eb2b6e6c62b429bc6e6e922ff31f715/azure-iot-edge-runtime-ctl-1.0.0rc11.tar.gz$
    Found link https://pypi.python.org/packages/d5/24/70683448243956541f32f2c2a77b12c9f9d91c84b69a969842ff7001573b/azure-iot-edge-runtime-ctl-1.0.0rc13.tar.gz$
  Ignoring link https://pypi.python.org/packages/22/51/41c972427bb410521fc72772c59a140fe841f7c51edb45aefc44e2d202ad/azure_iot_edge_runtime_ctl-1.0.0rc14-py2.p$
  Ignoring link https://pypi.python.org/packages/57/61/1716c5d31f5db0e66e02847ea288ee7b22053ae8dcbcb2b6720ddc41e4e4/azure_iot_edge_runtime_ctl-1.0.0rc11-py2.p$
  Ignoring link https://pypi.python.org/packages/85/12/2de6ec3f9b99f70483531ebbcd81992cc0b0dec07cce64c4342094a31b67/azure-iot-edge-runtime-ctl-1.0.0rc14.tar.g$
  Ignoring link https://pypi.python.org/packages/9c/1f/900bb21d98a332083e3ff0ee2b34b3425f22677c32719ed77f9b9803c299/azure_iot_edge_runtime_ctl-1.0.0rc13-py2.p$
  Ignoring link https://pypi.python.org/packages/d2/89/423440eb2576d0884e809cd9521a5eb2b6e6c62b429bc6e6e922ff31f715/azure-iot-edge-runtime-ctl-1.0.0rc11.tar.g$
  Ignoring link https://pypi.python.org/packages/d5/24/70683448243956541f32f2c2a77b12c9f9d91c84b69a969842ff7001573b/azure-iot-edge-runtime-ctl-1.0.0rc13.tar.g$
  Could not find a version that satisfies the requirement azure-iot-edge-runtime-ctl (from versions: 1.0.0rc14, 1.0.0rc11, 1.0.0rc14, 1.0.0rc13, 1.0.0rc11, 1.$
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
No distributions matching the version for azure-iot-edge-runtime-ctl
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for azure-iot-edge-runtime-ctl
```

If I try to force a version by doing sudo pip install -U azure-iot-edge-runtime-ctl==1.0.0rc14, I get this from the pip.log:
_Shortened for brevity_
```
Downloading from URL https://pypi.python.org/packages/db/38/8f3582eb075c3eaf2a5f2a97d8ebcf67f50dc94309d5b78707a13ffc1802/websocket_client-0.44.0-py2.py3-non$
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1091, in prepare_files
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 811, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(self.req)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 564, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 436, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
IndexError: list index out of range
```

Details of the Linux host:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
```

**Comment by darobs** [comment]
I'm unsure of what exactly is going on, from [the package index page](https://pypi.python.org/pypi/azure-iot-edge-runtime-ctl), these are our listed requirements.

Requires Distributions 
 - check-manifest; extra == 'dev' 
 - pypiwin32; sys_platform == "win32" 
 - pyOpenSSL 
 - enum34 
 - docker[tls] (==2.6) 

Perhaps, running
```sh
sudo pip install --upgrade setuptools pip
```

would help?

**Comment by mrohera** [comment]
Hello murdockcrc,
Have you made any progress on your reported problem?

Another point to consider, I had seen a failure to install this utility on trusty which had an older installation of Python (< 2.7.6). I do not have a screen grab to see if it matched your symptoms unfortunately.

To get around this, I installed a newer version of Python 2.7 (specifically 2.7.14) which I built from source. I had to build from source as opposed to updating the package, because the latest Python version was 2.7.5 at the time I ran into this problem. See [https://packages.ubuntu.com/trusty/python](https://packages.ubuntu.com/trusty/python)  

Could you consider updating your version of python, retrying the install and let us know how it goes?

Thanks.

**Comment by grtn316** [comment]
I just made this. Hopefully it will help:

https://github.com/grtn316/iotedgectl_preview-snap

**Comment by villepalo** [comment]
I had the same issue on ubuntu 16.04.
running `sudo pip install --upgrade setuptools pip` did solve the problem.

**Comment by myagley** [comment]
This should be fixed in the latest version of the iotedgectl. Please reopen if you are still running into issues.
