### ISSUE TITLE
Precondition failed error on Pi

### ISSUE THREAD

**Issue by jonbgallant** [Azure/iot-edge#440]
After deploy, run this on Pi:
`docker logs edgeAgent -f`

And got this:

```

Microsoft.Azure.Devices.Common.Exceptions.PreconditionFailedException: Precondition failed: {"Message":"ErrorCode:PreconditionFailed;                                                                                                     PreconditionFailed","ExceptionMessage":"Tracking ID:29e91aa72a1e491b88b2c3b3da2baaee-G:5-TimeStamp:12/11/2017 01:55:00"}
   at Microsoft.Azure.Devices.HttpClientHelper.<ExecuteAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.HttpClientHelper.<PutAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleIdentityLifecycleManager.<UpdateServiceModulesIdentityAsync>d__8.MoveNext() in                                                                                                      /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleIdentityLifecycleManager.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleIdentityLifecycleManager.<GetModuleIdentitiesAsync>d__4.MoveNext() in /opt/vsts                                                                                                     /work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleIdentityLifecycleManager.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.<ReconcileAsync>d__9.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Az                                                                                                     ure.Devices.Edge.Agent.Core/Agent.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.<ReconcileAsync>d__9.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Az                                                                                                     ure.Devices.Edge.Agent.Core/Agent.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.<MainAsync>d__4.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Az                                                                                                     ure.Devices.Edge.Agent.Service/Program.cs:line 128

```

**Comment by myagley** [comment]
Is this still an issue? Closing for now but will reopen if this is still occurring.
