### ISSUE TITLE
[V2][Preview] Unable to pull custom module from Private repo

### ISSUE THREAD

**Issue by surabhshah** [Azure/iot-edge#449]
Hello,

I am facing a very strange issue. I have created a custom module and pushed it up on the Azure Container Registry (Private access) and Docker hub registry (Public access). When I am trying to set the modules on a windows container, all the modules having public access are deployed perfectly but the modules with private access do not deploy and the status shown on the portal remains as **pending deployment**. However, everything was working fine until yesterday.

Screen for Azure portal log below

![111](https://user-images.githubusercontent.com/8298707/34256867-5af15e8a-e67d-11e7-97b6-d8742237c17a.PNG)

Please note, I have logged into the docker using the Azure Container Registry credentials.

Also, please find a snippet of exception occurring in **edgeAgent** module as below

> 2017-12-21 15:14:57.527 +05:30 [ERR] - Step failed in deployment 10, continuing execution. Failure when running command Command Group: (
>   [docker pull edgecheckreg.azurecr.io/formattermodule:v2]
>   [docker create --name formattermodule edgecheckreg.azurecr.io/formattermodule:v2]
>   [docker start formattermodule]
> )
> 2017-12-21 15:14:57.527 +05:30 [INF] - Plan execution ended for deployment 10
> 2017-12-21 15:14:57.527 +05:30 [ERR] - Edge agent plan execution failed.
> System.AggregateException: One or more errors occurred. (Docker API responded with status code=InternalServerError, image=edgecheckreg.azurecr.io/formattermodule, tag=v2. Check container registry (possible authorization failure or container registry down).) ---> Microsoft.Azure.Devices.Edge.Agent.Docker.InternalServerErrorException: Docker API responded with status code=InternalServerError, image=edgecheckreg.azurecr.io/formattermodule, tag=v2. Check container registry (possible authorization failure or container registry down). ---> Docker.DotNet.DockerApiException: Docker API responded with status code=InternalServerError, response=
>    at Docker.DotNet.DockerClient.HandleIfErrorResponse(HttpStatusCode statusCode, String responseBody, IEnumerable`1 handlers)
>    at Docker.DotNet.DockerClient.<MakeRequestForStreamAsync>d__50.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.DotNet.Models.StreamUtil.<MonitorStreamForMessagesAsync>d__1`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Devices.Edge.Agent.Docker.Commands.PullCommand.<ExecuteAsync>d__6.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/commands/PullCommand.cs:line 53
>    --- End of inner exception stack trace ---
>    at Microsoft.Azure.Devices.Edge.Agent.Docker.Commands.PullCommand.<ExecuteAsync>d__6.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/commands/PullCommand.cs:line 69
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.<ExecuteAsync>d__6.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 66
> --- End of stack trace from previous location where exception was thrown ---
> 

Thanks,
Surabh

**Comment by darobs** [comment]
Did you log into the repository using `docker login`?

If you logged in using Docker, I would recommend trying using the `iotedgectl login` command, or if you have a config.json add a deployment.registries section.

One common problem I've had, if you used `iotedgectl login` and then run `iotedgectl setup` again, the docker registry information is not kept, and you have to re-enter the information.

**Comment by surabhshah** [comment]
Hi David @darobs ,

Thanks for a prompt reply. That works. It was really silly of me running _setup_ after the _login_ command. Thanks for rightly pointing it out.

Regards,
Surabh

**Comment by darobs** [comment]
It's not that silly at all, I've done it more than once. 

Also, there is an option `--docker-registries` in the setup command which would allow you to specify the docker registries at the same time.

**Comment by surabhshah** [comment]
Ha ha, thanks that is a really useful info, would definitely give it a try.

Best Regards,
Surabh

**Comment by ohmyheartbeat** [comment]
2018-01-15 10:51:14.024 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.DeviceClient] - Device client for edge agent created.
2018-01-15 10:51:14.155 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.DeviceClient] - Edge agent attempting to connect to IoT Hub via AMQP...
2018-01-15 10:51:15.350 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.ConfigSources.TwinConfigSource] - TwinConfigSource Created
2018-01-15 10:51:15.356 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.FileBackupConfigSource] - Edge agent config backup created here - backup.json
2018-01-15 10:51:20.048 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Service.Modules.AgentModule] - Created persistent store at /tmp/edgeAgent
2018-01-15 10:51:22.083 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Edge agent created.
2018-01-15 10:51:23.841 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.Reporters.IoTHubReporter] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-15 10:51:27.160 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Connection status changed to Connected with reason Connection_Ok
2018-01-15 10:51:27.328 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.DeviceClient] - Edge agent connected to IoT Hub via AMQP.
2018-01-15 10:51:28.708 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Edge agent updated deployment config from desired properties.
2018-01-15 10:51:28.709 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Updated edge agent configuration from twin.
2018-01-15 10:51:31.847 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Planners.HealthRestartPlanner] - HealthRestartPlanner created Plan, with 4 command(s).
2018-01-15 10:51:31.917 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner] - Plan execution started for deployment 6
2018-01-15 10:51:31.919 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner] - Received new deployment 6
2018-01-15 10:51:32.165 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory] - Executing command: "Command Group: (
  [docker pull mlcrpacr3d304580ce69.azurecr.io/machinelearningmodule:1]
  [docker create --name machinelearningmodule mlcrpacr3d304580ce69.azurecr.io/machinelearningmodule:1]
  [docker start machinelearningmodule]
)"
2018-01-15 10:51:32.176 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory] - Executing command: "docker pull mlcrpacr3d304580ce69.azurecr.io/machinelearningmodule:1"


but i not thorw exception

**Comment by ohmyheartbeat** [comment]
the log just stay here  with docker pull ....

**Comment by ohmyheartbeat** [comment]
I use the iotedgectl login set the container Registery AccessKeys
