### ISSUE TITLE
IoT Edge Runtime snap issue

### ISSUE THREAD

**Issue by grtn316** [Azure/iot-edge#454]
Hello,

I have a requirement to setup the iot edge runtime on ubuntu core 16.04, using snappy. I was unable to find a existing snap, so I made one: https://github.com/grtn316/iotedgectl_preview-snap/blob/master/README.md. Ubuntu will not let me publish it to the store because it requires elevated permissions to use docker. 

Anyways, it appears to function normal other than never checking in as a device and actually sending data. It starts up, pulls images, starts the containres and logs start rolling in. 

What I did notice is that the hub is trying to connect over AMQP and the ports that are configured for the docker container are: HTTPS & MQTT (0.0.0.0:443->443/tcp, 0.0.0.0:8883->8883/tcp).

 **microsoft/azureiotedge-hub:1.0-preview**

`Edge Hub Server Certificate File: /mnt/edgehub/edge-hub-server.cert.pfx
Edge Hub CA Server Certificate File: /mnt/edgehub/edge-chain-ca.cert.pem
SSL_CERTIFICATE_PATH=/mnt/edgehub
SSL_CERTIFICATE_NAME=edge-hub-server.cert.pfx
Executing: cp /mnt/edgehub/edge-chain-ca.cert.pem /usr/local/share/ca-certificates/edge-chain-ca.crt
Executing: update-ca-certificates
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Certificates installed successfully!
2018-01-03 13:33:10.555 +00:00 [INF] - User profile is available. Using '"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest.
2018-01-03 13:33:10.845 +00:00 [INF] - Starting Edge Hub.
2018-01-03 13:33:10.853 +00:00 [INF] - Version - 1.0.0-preview017.8307729 (ed4d58d0308db5d6cc2fbc5d5ece7de516683e58)
2018-01-03 13:33:10.854 +00:00 [INF] -
2018-01-03 13:33:10.862 +00:00 [INF] - Initializing configuration
2018-01-03 13:33:12.358 +00:00 [INF] - Created persistent store at /tmp/edgeHub
2018-01-03 13:33:12.676 +00:00 [INF] - Attempting to connect to IoT Hub for client EdgeV2Simulator/$edgeHub via AMQP...
2018-01-03 13:33:16.735 +00:00 [INF] - Connected to IoT Hub for client EdgeV2Simulator/$edgeHub via AMQP, with client operation timeout 60000.
2018-01-03 13:33:16.778 +00:00 [INF] - Created cloud connection for client EdgeV2Simulator/$edgeHub
2018-01-03 13:33:16.872 +00:00 [INF] - New device connection for device EdgeV2Simulator/$edgeHub
2018-01-03 13:33:18.288 +00:00 [INF] - Started task to cleanup processed and stale messages
2018-01-03 13:33:18.290 +00:00 [INF] - Created new message store
2018-01-03 13:33:20.136 +00:00 [INF] - Obtained edge hub config from module twin
2018-01-03 13:33:20.768 +00:00 [INF] - Set the following 1 route(s) in edge hub - route
2018-01-03 13:33:20.774 +00:00 [INF] - Updated message store TTL to 7200 seconds
2018-01-03 13:33:20.776 +00:00 [INF] - Updated the edge hub store and forward configuration
2018-01-03 13:33:20.779 +00:00 [INF] - Initialized edge hub configuration
2018-01-03 13:33:20.779 +00:00 [INF] - Starting Http Server
2018-01-03 13:33:21.854 +00:00 [INF] - Starting MQTT Server
2018-01-03 13:33:22.018 +00:00 [INF] - Starting
2018-01-03 13:33:22.329 +00:00 [INF] - Initializing TLS endpoint on port 8883.
2018-01-03 13:33:22.704 +00:00 [INF] - Started
2018-01-03 13:33:26.823 +00:00 [INF] - Attempting to connect to IoT Hub for client EdgeV2Simulator/tempSensor via AMQP...
2018-01-03 13:33:26.904 +00:00 [INF] - New token requested by client EdgeV2Simulator/tempSensor, but using existing token as it is usable.
2018-01-03 13:33:27.161 +00:00 [INF] - Connected to IoT Hub for client EdgeV2Simulator/tempSensor via AMQP, with client operation timeout 60000.
2018-01-03 13:33:27.163 +00:00 [INF] - Created cloud connection for client EdgeV2Simulator/tempSensor
2018-01-03 13:33:27.172 +00:00 [INF] - New cloud connection created for device EdgeV2Simulator/tempSensor
2018-01-03 13:33:27.180 +00:00 [INF] - Successfully authenticated device EdgeV2Simulator/tempSensor
2018-01-03 13:33:27.184 +00:00 [INF] - Successfully generated identity for clientId EdgeV2Simulator/tempSensor and username f51v802/EdgeV2Simulator/tempSensor/api-version=2017-06-30&DeviceClientType=Microsoft.Azure.Devices.Client%2F1.7.0-preview-002%20%28.NET%20Core%204.6.00001.0%3B%20Linux%204.4.0-98-generic%20%23121-Ubuntu%20SMP%20Tue%20Oct%2010%2014%3A24%3A03%20UTC%202017%3B%20X64%29
2018-01-03 13:33:27.199 +00:00 [INF] - ClientAuthenticated, EdgeV2Simulator/tempSensor, 6ed8a48e
2018-01-03 13:33:27.402 +00:00 [INF] - New device connection for device EdgeV2Simulator/tempSensor
2018-01-03 13:33:27.513 +00:00 [INF] - Bind device proxy for device EdgeV2Simulator/tempSensor
2018-01-03 13:33:27.518 +00:00 [INF] - Binding message channel for device Id EdgeV2Simulator/tempSensor
2018-01-03 13:33:33.436 +00:00 [INF] - Attempting to connect to IoT Hub for client EdgeV2Simulator/delwinsModule via AMQP...
2018-01-03 13:33:33.440 +00:00 [INF] - New token requested by client EdgeV2Simulator/delwinsModule, but using existing token as it is usable.
2018-01-03 13:33:33.600 +00:00 [INF] - Connected to IoT Hub for client EdgeV2Simulator/delwinsModule via AMQP, with client operation timeout 60000.
2018-01-03 13:33:33.602 +00:00 [INF] - Created cloud connection for client EdgeV2Simulator/delwinsModule
2018-01-03 13:33:33.603 +00:00 [INF] - New cloud connection created for device EdgeV2Simulator/delwinsModule
2018-01-03 13:33:33.603 +00:00 [INF] - Successfully authenticated device EdgeV2Simulator/delwinsModule
2018-01-03 13:33:33.604 +00:00 [INF] - Successfully generated identity for clientId EdgeV2Simulator/delwinsModule and username f51v802/EdgeV2Simulator/delwinsModule/api-version=2017-06-30&DeviceClientType=Microsoft.Azure.Devices.Client%2F1.7.0-preview-002%20%28.NET%20Core%204.6.00001.0%3B%20Linux%204.4.0-98-generic%20%23121-Ubuntu%20SMP%20Tue%20Oct%2010%2014%3A24%3A03%20UTC%202017%3B%20X64%29
2018-01-03 13:33:33.646 +00:00 [INF] - ClientAuthenticated, EdgeV2Simulator/delwinsModule, 7cf87068
2018-01-03 13:33:33.648 +00:00 [INF] - New device connection for device EdgeV2Simulator/delwinsModule
2018-01-03 13:33:33.651 +00:00 [INF] - Bind device proxy for device EdgeV2Simulator/delwinsModule
2018-01-03 13:33:33.651 +00:00 [INF] - Binding message channel for device Id EdgeV2Simulator/delwinsModule
2018-01-03 13:42:32.349 +00:00 [INF] - Obtained edge hub config patch update from module twin
2018-01-03 13:42:32.575 +00:00 [INF] - Updating edge hub configuration
2018-01-03 13:42:32.713 +00:00 [INF] - Set the following 1 route(s) in edge hub - route
2018-01-03 13:42:32.714 +00:00 [INF] - Updated message store TTL to 7200 seconds
2018-01-03 13:42:32.714 +00:00 [INF] - Updated the edge hub store and forward configuration
2018-01-03 13:42:37.422 +00:00 [WRN] - Closing connection for device: EdgeV2Simulator/delwinsModule, Microsoft.Azure.Devices.ProtocolGateway.ProtocolGatewayException: Channel closed.,
2018-01-03 13:42:37.445 +00:00 [INF] - Disposing MessagingServiceClient for device Id EdgeV2Simulator/delwinsModule because of exception - Microsoft.Azure.Devices.ProtocolGateway.ProtocolGatewayException: Channel closed.
2018-01-03 13:42:37.475 +00:00 [INF] - Setting device proxy inactive for device Id EdgeV2Simulator/delwinsModule
2018-01-03 13:42:37.555 +00:00 [INF] - Closing receiver for device EdgeV2Simulator/delwinsModule
2018-01-03 13:42:37.856 +00:00 [INF] - Closed cloud proxy for device EdgeV2Simulator/delwinsModule
2018-01-03 13:42:37.862 +00:00 [INF] - Device connection removed for device EdgeV2Simulator/delwinsModule
2018-01-03 13:42:37.878 +00:00 [INF] - Remove device connection for device EdgeV2Simulator/delwinsModule
2018-01-03 13:43:18.321 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 13:43:19.169 +00:00 [INF] - Cleaned up 227 messages from queue for endpoint iothub
2018-01-03 13:45:06.960 +00:00 [ERR] - LEAK: IByteBuffer.Release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, set environment variable io.netty.leakDetection.level to advanced or set ResourceLeakDetector.Level in code. See http://netty.io/wiki/reference-counted-objects.html for more information.
2018-01-03 13:53:49.169 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 13:53:49.567 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-03 14:04:19.572 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 14:04:20.006 +00:00 [INF] - Cleaned up 125 messages from queue for endpoint iothub
2018-01-03 14:14:50.006 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 14:14:50.407 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-03 14:25:20.412 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 14:25:20.821 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-03 14:28:38.010 +00:00 [INF] - Existing token not found for EdgeV2Simulator/tempSensor. Getting new token from the client...
2018-01-03 14:28:38.036 +00:00 [WRN] - Closing connection for device: EdgeV2Simulator/tempSensor, Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device EdgeV2Simulator/tempSensor.,
2018-01-03 14:28:38.037 +00:00 [INF] - Disposing MessagingServiceClient for device Id EdgeV2Simulator/tempSensor because of exception - Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device EdgeV2Simulator/tempSensor.
2018-01-03 14:28:38.046 +00:00 [INF] - Closing device proxy for device Id EdgeV2Simulator/tempSensor
2018-01-03 14:28:38.047 +00:00 [INF] - Device connection removed for device EdgeV2Simulator/tempSensor
2018-01-03 14:28:38.495 +00:00 [INF] - Obtained new token for client EdgeV2Simulator/tempSensor that expires in 00:59:59.5043680
2018-01-03 14:28:38.496 +00:00 [INF] - New cloud connection created for device EdgeV2Simulator/tempSensor
2018-01-03 14:28:38.497 +00:00 [INF] - Successfully authenticated device EdgeV2Simulator/tempSensor
2018-01-03 14:28:38.497 +00:00 [INF] - Successfully generated identity for clientId EdgeV2Simulator/tempSensor and username f51v802/EdgeV2Simulator/tempSensor/api-version=2017-06-30&DeviceClientType=Microsoft.Azure.Devices.Client%2F1.7.0-preview-002%20%28.NET%20Core%204.6.00001.0%3B%20Linux%204.4.0-98-generic%20%23121-Ubuntu%20SMP%20Tue%20Oct%2010%2014%3A24%3A03%20UTC%202017%3B%20X64%29
2018-01-03 14:28:38.498 +00:00 [INF] - ClientAuthenticated, EdgeV2Simulator/tempSensor, 4136b000
2018-01-03 14:28:38.499 +00:00 [INF] - New device connection for device EdgeV2Simulator/tempSensor
2018-01-03 14:28:38.502 +00:00 [INF] - Bind device proxy for device EdgeV2Simulator/tempSensor
2018-01-03 14:28:38.502 +00:00 [INF] - Binding message channel for device Id EdgeV2Simulator/tempSensor
2018-01-03 14:35:50.824 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 14:35:51.289 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-03 14:46:21.290 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 14:46:21.704 +00:00 [INF] - Cleaned up 125 messages from queue for endpoint iothub
2018-01-03 14:56:51.703 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 14:56:52.088 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-03 15:07:22.092 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 15:07:22.509 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-03 15:17:52.507 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 15:17:52.899 +00:00 [INF] - Cleaned up 125 messages from queue for endpoint iothub
2018-01-03 15:28:22.898 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 15:28:23.331 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-03 15:33:12.369 +00:00 [INF] - Starting compaction of stores
2018-01-03 15:33:12.373 +00:00 [INF] - Starting compaction of store default
2018-01-03 15:33:12.380 +00:00 [INF] - Starting compaction of store messages
2018-01-03 15:33:12.440 +00:00 [INF] - Starting compaction of store twins
2018-01-03 15:33:12.456 +00:00 [INF] - Starting compaction of store sessions
2018-01-03 15:33:12.467 +00:00 [INF] - Starting compaction of store iothub
2018-01-03 15:33:12.483 +00:00 [INF] - Starting compaction of store checkpoints
2018-01-03 15:38:30.588 +00:00 [WRN] - Closing connection for device: EdgeV2Simulator/tempSensor, Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device EdgeV2Simulator/tempSensor.,
2018-01-03 15:38:30.588 +00:00 [INF] - Disposing MessagingServiceClient for device Id EdgeV2Simulator/tempSensor because of exception - Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device EdgeV2Simulator/tempSensor.
2018-01-03 15:38:30.594 +00:00 [INF] - Closing device proxy for device Id EdgeV2Simulator/tempSensor
2018-01-03 15:38:30.595 +00:00 [INF] - Closing receiver for device EdgeV2Simulator/tempSensor
2018-01-03 15:38:30.608 +00:00 [ERR] - Error closing cloud proxy for device EdgeV2Simulator/tempSensor
Microsoft.Azure.Devices.Client.Exceptions.AssertionFailedException: An unexpected failure occurred. Applications should not attempt to handle this error. For diagnostic purposes, this English message is associated with the failure: The number of devices should be greater than zero.
   at Microsoft.Azure.Devices.Client.Fx.AssertAndThrow(String description)
   at Microsoft.Azure.Devices.Client.IotHubDeviceScopeConnectionPool.RemoveDeviceFromConnection(IotHubDeviceMuxConnection iotHubDeviceMuxConnection, String deviceId)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.<CloseAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.GateKeeperDelegatingHandler.<CloseAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.<CloseAsync>d__8.MoveNext() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 46
2018-01-03 15:38:30.652 +00:00 [INF] - Device connection removed for device EdgeV2Simulator/tempSensor
2018-01-03 15:38:30.754 +00:00 [INF] - Attempting to connect to IoT Hub for client EdgeV2Simulator/tempSensor via AMQP...
2018-01-03 15:38:30.758 +00:00 [INF] - New token requested by client EdgeV2Simulator/tempSensor, but using existing token as it is usable.
2018-01-03 15:38:30.911 +00:00 [INF] - Connected to IoT Hub for client EdgeV2Simulator/tempSensor via AMQP, with client operation timeout 60000.
2018-01-03 15:38:30.912 +00:00 [INF] - Closing receiver for device EdgeV2Simulator/tempSensor
2018-01-03 15:38:30.912 +00:00 [INF] - Closed cloud proxy for device EdgeV2Simulator/tempSensor
2018-01-03 15:38:30.913 +00:00 [INF] - New cloud connection created for device EdgeV2Simulator/tempSensor
2018-01-03 15:38:30.914 +00:00 [INF] - Successfully authenticated device EdgeV2Simulator/tempSensor
2018-01-03 15:38:30.914 +00:00 [INF] - Successfully generated identity for clientId EdgeV2Simulator/tempSensor and username f51v802/EdgeV2Simulator/tempSensor/api-version=2017-06-30&DeviceClientType=Microsoft.Azure.Devices.Client%2F1.7.0-preview-002%20%28.NET%20Core%204.6.00001.0%3B%20Linux%204.4.0-98-generic%20%23121-Ubuntu%20SMP%20Tue%20Oct%2010%2014%3A24%3A03%20UTC%202017%3B%20X64%29
2018-01-03 15:38:30.914 +00:00 [INF] - ClientAuthenticated, EdgeV2Simulator/tempSensor, 6689b7e7
2018-01-03 15:38:30.916 +00:00 [INF] - New device connection for device EdgeV2Simulator/tempSensor
2018-01-03 15:38:30.918 +00:00 [INF] - Bind device proxy for device EdgeV2Simulator/tempSensor
2018-01-03 15:38:30.919 +00:00 [INF] - Binding message channel for device Id EdgeV2Simulator/tempSensor
2018-01-03 15:38:53.335 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 15:38:53.470 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-03 15:49:23.477 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 15:49:23.883 +00:00 [INF] - Cleaned up 125 messages from queue for endpoint iothub
2018-01-03 15:59:53.888 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 15:59:54.327 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-03 16:10:24.332 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 16:10:24.760 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-03 16:20:54.763 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 16:20:55.249 +00:00 [INF] - Cleaned up 125 messages from queue for endpoint iothub
2018-01-03 16:31:25.258 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 16:31:25.707 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-03 16:41:55.713 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-03 16:41:56.154 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub`

 **microsoft/azureiotedge-agent:1.0-preview**
`2018-01-03 13:32:13.225 +00:00 [INF] - Starting module management agent.
2018-01-03 13:32:14.161 +00:00 [INF] - Version - 1.0.0-preview017.8307729 (ed4d58d0308db5d6cc2fbc5d5ece7de516683e58)
2018-01-03 13:32:14.163 +00:00 [INF] -
2018-01-03 13:32:14.592 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via AMQP...
2018-01-03 13:32:15.333 +00:00 [INF] - Edge agent config backup created here - backup.json
2018-01-03 13:32:16.901 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
2018-01-03 13:32:19.155 +00:00 [INF] - Edge agent connected to IoT Hub via AMQP.
2018-01-03 13:32:19.373 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-03 13:32:26.136 +00:00 [INF] - Plan execution started for deployment 3
2018-01-03 13:32:26.404 +00:00 [INF] - Executing command: "Command Group: (
  [docker pull microsoft/azureiotedge-simulated-temperature-sensor:1.0-preview]
  [docker create --name delwinsModule microsoft/azureiotedge-simulated-temperature-sensor:1.0-preview]
  [docker start delwinsModule]
)"
2018-01-03 13:32:26.416 +00:00 [INF] - Executing command: "docker pull microsoft/azureiotedge-simulated-temperature-sensor:1.0-preview"
2018-01-03 13:32:31.240 +00:00 [INF] - Executing command: "docker create --name delwinsModule microsoft/azureiotedge-simulated-temperature-sensor:1.0-preview"
2018-01-03 13:32:31.403 +00:00 [INF] - Executing command: "docker start delwinsModule"
2018-01-03 13:32:32.408 +00:00 [INF] - Executing command: "Command Group: (
  [docker pull microsoft/azureiotedge-hub:1.0-preview]
  [docker create --name edgeHub microsoft/azureiotedge-hub:1.0-preview]
  [docker start edgeHub]
)"
2018-01-03 13:32:32.409 +00:00 [INF] - Executing command: "docker pull microsoft/azureiotedge-hub:1.0-preview"
2018-01-03 13:32:54.498 +00:00 [INF] - Executing command: "docker create --name edgeHub microsoft/azureiotedge-hub:1.0-preview"
2018-01-03 13:32:54.626 +00:00 [INF] - Executing command: "docker start edgeHub"
2018-01-03 13:32:55.815 +00:00 [INF] - Executing command: "Command Group: (
  [docker pull microsoft/azureiotedge-simulated-temperature-sensor:1.0-preview]
  [docker create --name tempSensor microsoft/azureiotedge-simulated-temperature-sensor:1.0-preview]
  [docker start tempSensor]
)"
2018-01-03 13:32:55.816 +00:00 [INF] - Executing command: "docker pull microsoft/azureiotedge-simulated-temperature-sensor:1.0-preview"
2018-01-03 13:32:57.270 +00:00 [INF] - Executing command: "docker create --name tempSensor microsoft/azureiotedge-simulated-temperature-sensor:1.0-preview"
2018-01-03 13:32:57.383 +00:00 [INF] - Executing command: "docker start tempSensor"
2018-01-03 13:32:58.408 +00:00 [INF] - Plan execution ended for deployment 3
2018-01-03 13:33:01.629 +00:00 [INF] - Updated reported properties
2018-01-03 13:42:37.189 +00:00 [INF] - Plan execution started for deployment 4
2018-01-03 13:42:37.196 +00:00 [INF] - Executing command: "docker stop -t 10 delwinsModule"
2018-01-03 13:42:37.620 +00:00 [INF] - Executing command: "docker rm delwinsModule"
2018-01-03 13:42:37.777 +00:00 [INF] - Executing command: "Reset health stats for module delwinsModule"
2018-01-03 13:42:37.790 +00:00 [INF] - Plan execution ended for deployment 4
2018-01-03 13:42:38.015 +00:00 [INF] - Updated reported properties
2018-01-03 15:32:16.907 +00:00 [INF] - Starting compaction of stores
2018-01-03 15:32:16.910 +00:00 [INF] - Starting compaction of store default
2018-01-03 15:32:16.916 +00:00 [INF] - Starting compaction of store mma
`

Please ignore the removal of a module. It was a duplicate instance of the tempsensor.

**Comment by grtn316** [comment]
So I debunked my theory of it being network related. I have successfully attached to the container and connected to the IoT Hub via telnet. I also checked netstat and I have 2 connections established to the IoT hub so I am not sure what is broke at this point.

**Comment by grtn316** [comment]
Update:

While I was troubleshooting, I noticed the IoT hub main page showed I had over 5000 messages received today...4 hours worth of troubleshooting.

Few problems:
-**The Device explorer shows the device to be disconnected and a blank for last activity time and last connection status...as if the device has never checked in.**
-When I go into the IoT Edge page and look at my device, it says "200 - OK". Once clicked into it, It shows my $endHub as pending modification (I told it to roll back to this image: microsoft/azureiotedge-hub:1.0.0-preview014-linux-amd64). This change has already been made over an hour ago.
-Modules say they are running

**Comment by myagley** [comment]
Hello,

I'm sorry you are having issues with IoT Edge. Can you help me understand the issue? It looks like both the Edge Agent and Edge Hub are connecting to IoT Hub and data is being received. Is the issue that the Azure Portal does not properly report the connection status of the edge device?

Thanks,
Mike

**Comment by grtn316** [comment]
Mike,

It turned out to be that exactly. I listened for messages and saw them coming in. I did not realize I needed to monitor the module status instead of the device status now.
