### ISSUE TITLE
Edge v2 SSL/Cert error in linux

### ISSUE THREAD

**Issue by grtn316** [Azure/iot-edge#479]
Hello,

I am experiencing an SSL/Cert error in the egeHub module which is preventing transmission of data from our sample tempSensor module after several hours of runtime.

Details:

OS: Ubuntu Core 16.04
Snap: https://github.com/grtn316/iotedgectl_preview-snap

edgeHub logs:

`2018-01-17 10:29:43.114 +00:00 [INF] - Connection id ""0HLATIKS73KVE"" bad request data: ""Invalid request line: 'GET / HTTP/1.1\x0A'""
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request line: 'GET / HTTP/1.1\x0A'
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.RejectRequestLine(Byte* requestLine, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, Byte* data, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.ParseRequest(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-01-17 10:38:14.032 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 10:38:14.311 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 10:48:44.312 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 10:48:44.762 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 10:59:14.764 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 10:59:15.267 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 11:09:45.269 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 11:09:45.705 +00:00 [INF] - Cleaned up 125 messages from queue for endpoint iothub
2018-01-17 11:18:06.616 +00:00 [ERR] - Uncaught exception from the OnConnectionAsync method of an IConnectionAdapter.
System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, Boolean isServer, Boolean remoteCertRequired)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionAdapter.<InnerOnConnectionAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.FrameConnection.<ApplyConnectionAdaptersAsync>d__43.MoveNext()
2018-01-17 11:20:15.714 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 11:20:16.117 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 11:29:17.571 +00:00 [INF] - Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionAdapter.<InnerOnConnectionAsync>d__8.MoveNext()
2018-01-17 11:30:46.126 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 11:30:46.531 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 11:36:45.265 +00:00 [INF] - Starting compaction of stores
2018-01-17 11:36:45.266 +00:00 [INF] - Starting compaction of store default
2018-01-17 11:36:45.266 +00:00 [INF] - Starting compaction of store twins
2018-01-17 11:36:45.267 +00:00 [INF] - Starting compaction of store iothub
2018-01-17 11:36:45.302 +00:00 [INF] - Starting compaction of store messages
2018-01-17 11:36:45.349 +00:00 [INF] - Starting compaction of store sessions
2018-01-17 11:36:45.443 +00:00 [INF] - Starting compaction of store checkpoints
2018-01-17 11:41:16.537 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 11:41:16.987 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 11:51:46.988 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 11:51:47.443 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 12:02:17.445 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 12:02:17.850 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 12:12:47.854 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 12:12:48.262 +00:00 [INF] - Cleaned up 125 messages from queue for endpoint iothub
2018-01-17 12:23:18.263 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 12:23:18.701 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 12:33:48.706 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 12:33:49.138 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 12:44:19.139 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 12:44:19.553 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 12:54:49.557 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 12:54:49.990 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 13:05:19.994 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 13:05:20.431 +00:00 [INF] - Cleaned up 125 messages from queue for endpoint iothub
2018-01-17 13:15:50.432 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 13:15:50.861 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 13:26:20.860 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 13:26:21.295 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 13:36:45.265 +00:00 [INF] - Starting compaction of stores
2018-01-17 13:36:45.265 +00:00 [INF] - Starting compaction of store default
2018-01-17 13:36:45.265 +00:00 [INF] - Starting compaction of store twins
2018-01-17 13:36:45.266 +00:00 [INF] - Starting compaction of store iothub
2018-01-17 13:36:45.354 +00:00 [INF] - Starting compaction of store messages
2018-01-17 13:36:45.402 +00:00 [INF] - Starting compaction of store sessions
2018-01-17 13:36:45.402 +00:00 [INF] - Starting compaction of store checkpoints
2018-01-17 13:36:51.298 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 13:36:51.713 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 13:39:16.919 +00:00 [INF] - Request starting HTTP/1.1 GET https://xxx.xxx.xxx.xx/  
2018-01-17 13:39:17.264 +00:00 [INF] - Request finished in 407.0361ms 401 text/html
2018-01-17 13:40:26.092 +00:00 [ERR] - Uncaught exception from the OnConnectionAsync method of an IConnectionAdapter.
System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, Boolean isServer, Boolean remoteCertRequired)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c__DisplayClass35_0.<AuthenticateAsServerAsync>b__0(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionAdapter.<InnerOnConnectionAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.FrameConnection.<ApplyConnectionAdaptersAsync>d__43.MoveNext()
2018-01-17 13:40:55.632 +00:00 [ERR] - Uncaught exception from the OnConnectionAsync method of an IConnectionAdapter.
System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, Boolean isServer, Boolean remoteCertRequired)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c__DisplayClass35_0.<AuthenticateAsServerAsync>b__0(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionAdapter.<InnerOnConnectionAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.FrameConnection.<ApplyConnectionAdaptersAsync>d__43.MoveNext()
2018-01-17 13:47:21.714 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 13:47:22.159 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 13:57:52.158 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 13:57:52.560 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 13:59:36.581 +00:00 [INF] - Request starting HTTP/1.1 GET https://xxx.xxx.xxx.xx/  
2018-01-17 13:59:36.587 +00:00 [INF] - Request finished in 6.3864ms 401 text/html
2018-01-17 14:08:22.565 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 14:08:23.008 +00:00 [INF] - Cleaned up 125 messages from queue for endpoint iothub
2018-01-17 14:18:53.012 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 14:18:53.442 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 14:19:35.481 +00:00 [INF] - Request starting HTTP/1.1 GET https://xxx.xxx.xxx.xx/  
2018-01-17 14:19:35.482 +00:00 [INF] - Request finished in 0.6478ms 401 text/html
2018-01-17 14:28:40.661 +00:00 [INF] - Failed to authenticate HTTPS connection.
System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c__DisplayClass35_0.<AuthenticateAsServerAsync>b__0(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionAdapter.<InnerOnConnectionAsync>d__8.MoveNext()
2018-01-17 14:29:23.446 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 14:29:23.849 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
2018-01-17 14:39:53.850 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-01-17 14:39:54.275 +00:00 [INF] - Cleaned up 126 messages from queue for endpoint iothub
`

**Comment by aribeironovaes** [comment]
Hi @grtn316 , 

I don't believe this is a cert issue, this is probably a dup of issue: https://github.com/Azure/iot-edge/issues/468

This issue shall be solved after the next release. 

Let's follow up on that issue and, after if we saw this after the release, let's reactivate this one. 

Thanks, 

Angelo Ribeiro.
