### ISSUE TITLE
looping Getting edge agent config ->Obtained edge agent config ->HealthRestartPlanner created Plan 

### ISSUE THREAD

**Issue by villepalo** [Azure/iot-edge#542]
My ingester module started to catch exceptions, exceptions are thrown from code like this.

            try
            {
                await deviceClient?.SendEventAsync("output1", new Message(Encoding.UTF8.GetBytes(message)));
            }
            catch (AggregateException exception)
            {
                Console.WriteLine($"Failed to send event: {exception}");
            }
            catch (ObjectDisposedException exception)
            {
                Console.WriteLine($"Failed to send event: {exception}");
            }
            catch (Exception exception)
            {
                Console.WriteLine($"Failed to send event: {exception}");
            }

Failed to send event: System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass79_0.<ApplyTimeout>b__2(Task t)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VariableApiIngester.Program.<SendVariableEvent>d__20.MoveNext() in c:\Users\Ingester.cs:line 327
Failed to send event: System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass79_0.<ApplyTimeout>b__2(Task t)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VariableApiIngester.Program.<SendVariableEvent>d__20.MoveNext() in c:\UsersIngester.cs:line 327
Failed to send event: System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass79_0.<ApplyTimeout>b__2(Task t)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VariableApiIngester.Program.<SendVariableEvent>d__20.MoveNext() in c:\Users\Ingester.cs:line 327

### edgeAgent seems to be in a loop

2018-03-15 08:48:53.572 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Getting edge agent config...
2018-03-15 08:48:53.582 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Obtained edge agent config
2018-03-15 08:48:53.583 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Planners.HealthRestartPlanner] - HealthRestartPlanner created Plan, with 0 command(s).
2018-03-15 08:48:58.591 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Getting edge agent config...
2018-03-15 08:48:58.605 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Obtained edge agent config
2018-03-15 08:48:58.610 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Planners.HealthRestartPlanner] - HealthRestartPlanner created Plan, with 0 command(s).
2018-03-15 08:49:03.615 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Getting edge agent config...
2018-03-15 08:49:03.632 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Obtained edge agent config
2018-03-15 08:49:03.634 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Planners.HealthRestartPlanner] - HealthRestartPlanner created Plan, with 0 command(s).
2018-03-15 08:49:08.647 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Getting edge agent config...
2018-03-15 08:49:08.653 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Obtained edge agent config
2018-03-15 08:49:08.657 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Planners.HealthRestartPlanner] - HealthRestartPlanner created Plan, with 0 command(s).
2018-03-15 08:49:13.663 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Getting edge agent config...
2018-03-15 08:49:13.669 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Obtained edge agent config
2018-03-15 08:49:13.686 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Planners.HealthRestartPlanner] - HealthRestartPlanner created Plan, with 0 command(s).

## edgeHub log

lots and lots of this:

2018-03-15 08:50:45.130 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.131 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.132 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.133 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.135 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.135 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.136 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.136 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.137 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.137 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.138 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.139 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.139 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.140 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.140 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.142 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.143 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 12115 with batch size 10.
2018-03-15 08:50:45.129 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint ttest-device/filter/input1 starting from 107833 with batch size 10.
2018-03-15 08:50:45.147 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint ttest-device/filter/input1 starting from 107833 with batch size 10.
2018-03-15 08:50:45.148 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint ttest-device/filter/input1 starting from 107833 with batch size 10.
2018-03-15 08:50:45.149 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint ttest-device/filter/input1 starting from 107833 with batch size 10.
2018-03-15 08:50:45.149 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint ttest-device/filter/input1 starting from 107833 with batch size 10.
2018-03-15 08:50:45.150 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint ttest-device/filter/input1 starting from 107833 with batch size 10.
2018-03-15 08:50:45.152 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint ttest-device/filter/input1 starting from 107833 with batch size 10.
2018-03-15 08:50:45.153 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint ttest-device/filter/input1 starting from 107833 with batch size 10.
2018-03-15 08:50:45.153 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint ttest-device/filter/input1 starting from 107833 with batch size 10.
2018-03-15 08:50:45.153 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint ttest-device/filter/input1 starting from 107833 with batch size 10.
2018-03-15 08:50:45.154 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint ttest-device/filter/input1 starting from 107833 with batch size 10.
2018-03-15 08:50:45.154 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint ttest-device/filter/input1 starting from 107833 with batch size 10.

**Comment by varunpuranik** [comment]
Hi villepalo, 
From the logs, it looks like the issue here is that your ingester module is not able to connect to the server and timing out. Are you doing a deviceClient.OpenAsync() before the send? My guess would be that the OpenAsync will also timeout, because it is not able to reach the server. 
So, just so I get this right - the ingester is a module deployed to the Edge device, right, or is it a downstream device? What connection string are you using for the deviceClient? Are you using the one in the EdgeHubConnectionString environment variable, as provided by the Edge runtime? 

One other question - what version of the EdgeAgent and the EdgeHub are you using? (the version should be at the top of the logs for those 2 modules). Please try to use the latest version - 1.0.0-preview021, since it has several bugs fixes. 

As for the EdgeAgent and EdgeHub logs - those are all expected logs from the normal processing that those modules do. Nothing out of the ordinary there.

**Comment by villepalo** [comment]
1. Ingester is a module deployed to the edge device.
2. Connection usually works, so it is not an issue with connection string, but yes, I'm using connection string from environment variables. 
3. As far as I know, OpenAsync was successfully executed. If the connection is not established, sending is not tried at all.

2018-03-15 06:38:38.074 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] - Starting module management agent.
2018-03-15 06:38:38.262 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] - Version - 1.0.0-preview021.10543704 (c87b52c93b13f03bf34da8d9ae650d5
5368ccecb)

**Comment by varunpuranik** [comment]
In that case, it seems like everything should work, especially if EdgeHub is not throwing any exceptions. One possibility is that the EdgeHub is dropping the connection after it is established, for some reason (even then, the SDK you are using on the module should try to re-open the connection automatically). Would you might copy-pasting the entire EdgeHub logs when you get the repro? That will hopefully tell us more about what is going on.
