### ISSUE TITLE
No data is emitted to the cloud from a privately build azureiotedge-simulated-temperature-sensor module

### ISSUE THREAD

**Issue by HenrikBach1** [Azure/iot-edge#578]
Hi @dariuszparys and @varunpuranik ,

Now I'm repeating the steps as suggested in #576 in a (new, but completely) copied `azureiotedge-simulated-temperature-sensor` project:

I've removed the previous images, but build, and pushed a new but identical image (with the same name and tag as given in #576) to my private repo:

```powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\tools\cygwin\home\hebh\projects\ddau-azure-iot-edge\src\prevas\azure\iot-edge\v2\azureiotedge-simulated-temperature-sensor> dir


    Directory: C:\tools\cygwin\home\hebh\projects\ddau-azure-iot-edge\src\pre
    vas\azure\iot-edge\v2\azureiotedge-simulated-temperature-sensor


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        4/11/2018   9:07 AM                .vscode
d-----        4/11/2018   9:07 AM                bin
d-----        4/11/2018   9:07 AM                Docker
d-----        4/11/2018   9:47 AM                obj
d-----        4/11/2018   9:07 AM                release
-a----         4/9/2018  11:25 AM           4832 .gitignore
-a----         4/9/2018  11:25 AM           1127 azureiotedge-simulated-tempe
                                                 rature-sensor.csproj
-a----         4/9/2018  11:25 AM            396 ControlCommand.cs
-a----         4/9/2018  11:25 AM           2147 DataGenerationPolicy.cs
-a----         4/9/2018  11:25 AM           1434 deployment.json
-a----         4/9/2018  11:25 AM           1720 DesiredPropertiesData.cs
-a----         4/9/2018  11:25 AM           1162 LICENSE
-a----         4/9/2018  11:25 AM            920 MessageBody.cs
-a----         4/9/2018  11:25 AM            617 multi-arch-manifest.yml
-a----         4/9/2018  11:25 AM           9044 Program.cs
-a----         4/9/2018  11:25 AM           5116 README.md
-a----         4/9/2018  11:25 AM           1653 TemperatureDataFactory.cs


PS C:\tools\cygwin\home\hebh\projects\ddau-azure-iot-edge\src\prevas\azure\iot-edge\v2\azureiotedg-edge\v2\azureiotedge-simulated-temperature-sensor> dotnet publish -o release -c Release
Microsoft (R) Build Engine version 15.6.84.34536 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 68,29 ms for C:\tools\cygwin\home\hebh\projects\ddau-azure-iot-edge\src\prevas\azure\iot-edge\v2\azureiotedge-simulated-temperature-sensor\azureiotedge-simulated-temperature-sensor.csproj.
  azureiotedge-simulated-temperature-sensor -> C:\tools\cygwin\home\hebh\projects\ddau-azure-iot-edge\src\prevas\azure\iot-edge\v2\azureiotedge-simulated-temperature-sensor\bin\Release\netcoreapp2.0\azureiotedge-simulated-temperature-sensor.dll
  azureiotedge-simulated-temperature-sensor -> C:\tools\cygwin\home\hebh\projects\ddau-azure-iot-edge\src\prevas\azure\iot-edge\v2\azureiotedge-simulated-temperature-sensor\release\
PS C:\tools\cygwin\home\hebh\projects\ddau-azure-iot-edge\src\prevas\azure\iot-edge\v2\azureiotedge-simulated-temperature-sensor> docker build -f .\Docker\linux-x64\Dockerfile --build-arg EXE_DIR=./release -t hebhddauazureiotedgetest1.azurecr.io/azureiotedge-simulated-temperature-sensor-linux-x64:0.1 .
Sending build context to Docker daemon  10.03MB
Step 1/5 : FROM microsoft/dotnet:2.0.5-runtime
 ---> 678967989e77
Step 2/5 : ARG EXE_DIR=.
 ---> Running in 15eeffb43024
Removing intermediate container 15eeffb43024
 ---> 14e0e3188f50
Step 3/5 : WORKDIR /app
Removing intermediate container f0f7dfa7db42
 ---> f0414d63f3c7
Step 4/5 : COPY $EXE_DIR/ ./
 ---> 9e289c8db9af
Step 5/5 : CMD ["dotnet", "azureiotedge-simulated-temperature-sensor.dll"]
 ---> Running in 45a4d8c6dd2b
Removing intermediate container 45a4d8c6dd2b
 ---> 5b1546d0cfed
Successfully built 5b1546d0cfed
Successfully tagged hebhddauazureiotedgetest1.azurecr.io/azureiotedge-simulated-temperature-sensor-linux-x64:0.1
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host.
All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
PS C:\tools\cygwin\home\hebh\projects\ddau-azure-iot-edge\src\prevas\azure\iot-edge\v2\azureiotedge-simulated-temperature-sensor>

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\tools\cygwin\home\hebh\projects\ddau-azure-iot-edge\src\prevas\azure\iot-edge\v2\azureiotedge-simulated-temperature-sensor> docker push hebhddauazureiotedgetest1.azurecr.io/azureiotedge-simulated-temperature-sensor-linux-x64:0.1
The push refers to repository [hebhddauazureiotedgetest1.azurecr.io/azureiotedge-simulated-temperature-sensor-linux-x64]
14be8b0241ea: Pushed
390fe01612f6: Pushed
6da20a5f2340: Pushed
9f72ee4e58ac: Pushed
9a3002c2d28f: Pushed
8568818b1f7f: Pushed
0.1: digest: sha256:61a368cbc2dc3a72abb538fde69e615e2f2383e571a44508f57d4b581bc7c990 size: 1580
PS C:\tools\cygwin\home\hebh\projects\ddau-azure-iot-edge\src\prevas\azure\iot-edge\v2\azureiotedge-simulated-temperature-sensor>
```

The deployment of the iot edge device is:

```json
{
    "moduleContent": {
        "$edgeAgent": {
            "properties.desired": {
                "schemaVersion": "1.0",
                "runtime": {
                    "type": "docker",
                    "settings": {
                        "minDockerVersion": "v1.25",
                        "loggingOptions": ""
                    }
                },
                "systemModules": {
                    "edgeAgent": {
                        "type": "docker",
                        "settings": {
                            "image": "microsoft/azureiotedge-agent:1.0-preview",
                            "createOptions": "{}"
                        }
                    },
                    "edgeHub": {
                        "type": "docker",
                        "status": "running",
                        "restartPolicy": "always",
                        "settings": {
                            "image": "microsoft/azureiotedge-hub:1.0-preview",
                            "createOptions": "{}"
                        }
                    }
                },
                "modules": {
                    "tempSensor": {
                        "version": "1.0",
                        "type": "docker",
                        "status": "running",
                        "restartPolicy": "always",
                        "settings": {
                            "image": "hebhddauazureiotedgetest1.azurecr.io/azureiotedge-simulated-temperature-sensor-linux-x64:0.1",
                            "createOptions": "{}"
                        }
                    }
                }
            }
        },
        "$edgeHub": {
            "properties.desired": {
                "schemaVersion": "1.0",
                "routes": {
                    "sensorToIoTHub": "FROM /* INTO $upstream"
                },
                "storeAndForwardConfiguration": {
                    "timeToLiveSecs": 7200
                }
            }
        }
    }
}
```

The module seems to emit data:

```log
$ docker logs -f tempSensor
Added Cert: /mnt/edgemodule/edge-device-ca.cert.pem
Connection String HostName=hebh-IoT-Hub-Test.azure-devices.net;GatewayHostName=cop382.prevas.se;DeviceId=IoT-Edge-Dell-Test-1;ModuleId=tempSensor;SharedAccessKey=qKepQse4Uayq58860Mn/Tywdcodkyrb+3C8T/n1LXxs=
IoT Hub module client initialized.
Updating desired properties {
  "$version": 1
}
Value for SendData = True
Value for SendInterval = 5
        04/11/2018 09:21:54> Sending message: 1, Body: {"machine":{"temperature":22.057491250479359,"pressure":1.1204736867634713},"ambient":{"temperature":21.468471918240411,"humidity":24},"timeCreated":"2018-04-11T09:21:54.7069287+00:00"}
        04/11/2018 09:21:59> Sending message: 2, Body: {"machine":{"temperature":22.692426413852921,"pressure":1.1928080724642569},"ambient":{"temperature":20.862763744016533,"humidity":25},"timeCreated":"2018-04-11T09:21:59.7582828+00:00"}
        04/11/2018 09:22:04> Sending message: 3, Body: {"machine":{"temperature":23.120081388563889,"pressure":1.2415282594566457},"ambient":{"temperature":21.490880557797329,"humidity":24},"timeCreated":"2018-04-11T09:22:04.7645645+00:00"}
        04/11/2018 09:22:09> Sending message: 4, Body: {"machine":{"temperature":23.733329819856834,"pressure":1.3113920047938166},"ambient":{"temperature":21.114874063811673,"humidity":24},"timeCreated":"2018-04-11T09:22:09.7713785+00:00"}
        04/11/2018 09:22:14> Sending message: 5, Body: {"machine":{"temperature":24.803252947774372,"pressure":1.433281981392017},"ambient":{"temperature":21.308050932738954,"humidity":25},"timeCreated":"2018-04-11T09:22:14.7853354+00:00"}
        04/11/2018 09:22:19> Sending message: 6, Body: {"machine":{"temperature":25.525474949286078,"pressure":1.5155604372604392},"ambient":{"temperature":21.280136383036215,"humidity":25},"timeCreated":"2018-04-11T09:22:19.7849113+00:00"}
        04/11/2018 09:22:24> Sending message: 7, Body: {"machine":{"temperature":25.787523855938357,"pressure":1.5454141101701926},"ambient":{"temperature":20.618820251020985,"humidity":25},"timeCreated":"2018-04-11T09:22:24.7887604+00:00"}
        04/11/2018 09:22:29> Sending message: 8, Body: {"machine":{"temperature":26.291961001833887,"pressure":1.6028816331203162},"ambient":{"temperature":21.104812187424308,"humidity":25},"timeCreated":"2018-04-11T09:22:29.7920360+00:00"}
        04/11/2018 09:22:34> Sending message: 9, Body: {"machine":{"temperature":27.385261444205078,"pressure":1.7274348480739961},"ambient":{"temperature":20.528453755671368,"humidity":24},"timeCreated":"2018-04-11T09:22:34.7883885+00:00"}
        04/11/2018 09:22:39> Sending message: 10, Body: {"machine":{"temperature":27.239541034791408,"pressure":1.7108337887737046},"ambient":{"temperature":21.328923534522264,"humidity":26},"timeCreated":"2018-04-11T09:22:39.7894418+00:00"}
        04/11/2018 09:22:44> Sending message: 11, Body: {"machine":{"temperature":27.569330236557562,"pressure":1.7484047104938996},"ambient":{"temperature":20.886578208481232,"humidity":25},"timeCreated":"2018-04-11T09:22:44.7877574+00:00"}
```

However, the module doesn't seem to output its data to the cloud!?

```log
[IoTHubMonitor] Start monitoring D2C message for all devices ...
[IoTHubMonitor] Created partition receiver [0] for consumerGroup [$Default]
[IoTHubMonitor] Created partition receiver [1] for consumerGroup [$Default]
```

Looking at the logs of the edgeHub indicates that something went wrong:

```log
$ docker logs --since 2018-04-11T09:05 --tail 0 -f edgeHub
2018-04-11 09:20:53.653 +00:00 [INF] - Attempting to connect to IoT Hub for client IoT-Edge-Dell-Test-1/tempSensor via AMQP...
2018-04-11 09:20:53.895 +00:00 [INF] - New token requested by client IoT-Edge-Dell-Test-1/tempSensor, but using existing token as it is usable.
2018-04-11 09:20:54.119 +00:00 [INF] - Connected to IoT Hub for client IoT-Edge-Dell-Test-1/tempSensor via AMQP, with client operation timeout 60000.
2018-04-11 09:20:54.119 +00:00 [INF] - Closing receiver for device IoT-Edge-Dell-Test-1/tempSensor
2018-04-11 09:20:54.119 +00:00 [INF] - Closed cloud proxy for device IoT-Edge-Dell-Test-1/tempSensor
2018-04-11 09:20:54.119 +00:00 [WRN] - Error adding subscription $iothub/twin/PATCH/properties/desired/# for client IoT-Edge-Dell-Test-1/tempSensor.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.SetupDesiredPropertyUpdatesAsync() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 136
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.SessionStatePersistenceProvider.<>c__DisplayClass10_0.<<ProcessSessionSubscriptions>b__0>d.MoveNext() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/SessionStatePersistenceProvider.cs:line 77
2018-04-11 09:20:54.120 +00:00 [WRN] - Error adding subscription $iothub/methods/POST/# for client IoT-Edge-Dell-Test-1/tempSensor.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.SetupCallMethodAsync() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 132
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.SessionStatePersistenceProvider.<>c__DisplayClass10_0.<<ProcessSessionSubscriptions>b__0>d.MoveNext() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/SessionStatePersistenceProvider.cs:line 66
2018-04-11 09:20:54.120 +00:00 [INF] - Set subscriptions from session state for IoT-Edge-Dell-Test-1/tempSensor on cloud reconnect
2018-04-11 09:20:54.121 +00:00 [INF] - New cloud connection created for device IoT-Edge-Dell-Test-1/tempSensor
2018-04-11 09:20:54.121 +00:00 [INF] - Successfully authenticated device IoT-Edge-Dell-Test-1/tempSensor
2018-04-11 09:20:54.121 +00:00 [INF] - Successfully generated identity for clientId IoT-Edge-Dell-Test-1/tempSensor and username cop382.prevas.se/IoT-Edge-Dell-Test-1/tempSensor/api-version=2017-06-30&DeviceClientType=Microsoft.Azure.Devices.Client%2F1.6.0-preview-001%20%28.NET%20Core%204.6.0.0%3B%20Linux%204.9.87-linuxkit-aufs%20%231%20SMP%20Wed%20Mar%2014%2015%3A12%3A16%20UTC%202018%3B%20X64%29
2018-04-11 09:20:54.121 +00:00 [INF] - ClientAuthenticated, IoT-Edge-Dell-Test-1/tempSensor, 0589bc42
2018-04-11 09:20:54.136 +00:00 [INF] - New device connection for device IoT-Edge-Dell-Test-1/tempSensor
2018-04-11 09:21:54.138 +00:00 [INF] - Bind device proxy for device IoT-Edge-Dell-Test-1/tempSensor
2018-04-11 09:21:54.138 +00:00 [INF] - Binding message channel for device Id IoT-Edge-Dell-Test-1/tempSensor
2018-04-11 09:21:54.139 +00:00 [INF] - Updating reported properties for IoT-Edge-Dell-Test-1/$edgeHub in cloud failed with error System.TimeoutException Operation timeout expired.
2018-04-11 09:21:54.234 +00:00 [INF] - Set subscriptions from session state for IoT-Edge-Dell-Test-1/tempSensor
2018-04-11 09:21:54.668 +00:00 [INF] - Set subscriptions from session state for IoT-Edge-Dell-Test-1/tempSensor
2018-04-11 09:21:54.685 +00:00 [INF] - Set subscriptions from session state for IoT-Edge-Dell-Test-1/tempSensor
2018-04-11 09:21:54.702 +00:00 [INF] - Set subscriptions from session state for IoT-Edge-Dell-Test-1/tempSensor
```

What did I do wrong?

Credentials to read from my private repo is: `hebhddauazureiotedgetest1\BRa596EKFNwM6gdH=wJhYLx6Fkx09DT4`.

Thank you.

/Henrik

**Comment by HenrikBach1** [comment]
Hi,

Now the data is streaming in...:

```log
[IoTHubMonitor] Created partition receiver [0] for consumerGroup [$Default]
[IoTHubMonitor] Created partition receiver [1] for consumerGroup [$Default]
[IoTHubMonitor] Message received from [IoT-Edge-Dell-Test-1]:
{
  "machine": {
    "temperature": 113.88994039659839,
    "pressure": 11.582398273030195
  },
  "ambient": {
    "temperature": 21.145600395577773,
    "humidity": 24
  },
  "timeCreated": "2018-04-11T10:47:47.7232083+00:00"
}
[IoTHubMonitor] Message received from [IoT-Edge-Dell-Test-1]:
{
  "machine": {
    "temperature": 113.86325793334423,
    "pressure": 11.579358498735418
  },
  "ambient": {
    "temperature": 21.08129058339693,
    "humidity": 26
  },
  "timeCreated": "2018-04-11T10:47:52.7439428+00:00"
}
```

Maybe a service disruption in Azure?...

Case is closed.

/Henrik

**Comment by HenrikBach1** [comment]
When the module is removed from the device, the edgeHub logs says:

```log
2018-04-11 11:16:53.099 +00:00 [INF] - Set subscriptions from session state for IoT-Edge-Dell-Test-1/tempSensor
2018-04-11 11:25:35.437 +00:00 [WRN] - Closing connection for device: IoT-Edge-Dell-Test-1/tempSensor, Microsoft.Azure.Devices.ProtocolGateway.ProtocolGatewayException: Channel closed.,
2018-04-11 11:25:35.437 +00:00 [INF] - Disposing MessagingServiceClient for device Id IoT-Edge-Dell-Test-1/tempSensor because of exception - Microsoft.Azure.Devices.ProtocolGateway.ProtocolGatewayException: Channel closed.
2018-04-11 11:25:35.437 +00:00 [INF] - Setting device proxy inactive for device Id IoT-Edge-Dell-Test-1/tempSensor
2018-04-11 11:25:35.438 +00:00 [INF] - Closing receiver for device IoT-Edge-Dell-Test-1/tempSensor
2018-04-11 11:25:35.441 +00:00 [ERR] - Error closing cloud proxy for device IoT-Edge-Dell-Test-1/tempSensor
Microsoft.Azure.Devices.Client.Exceptions.AssertionFailedException: An unexpected failure occurred. Applications should not attempt to handle this error. For diagnostic purposes, this English message is associated with the failure: The number of devices should be greater than zero.
   at Microsoft.Azure.Devices.Client.Fx.AssertAndThrow(String description)
   at Microsoft.Azure.Devices.Client.IotHubDeviceScopeConnectionPool.RemoveDeviceFromConnection(IotHubDeviceMuxConnection iotHubDeviceMuxConnection, String deviceId)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.<CloseAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.GateKeeperDelegatingHandler.<CloseAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.<CloseAsync>d__8.MoveNext() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 46
2018-04-11 11:25:35.443 +00:00 [INF] - Device connection removed for device IoT-Edge-Dell-Test-1/tempSensor
2018-04-11 11:25:35.446 +00:00 [INF] - Remove device connection for device IoT-Edge-Dell-Test-1/tempSensor
```

/Henrik
