### ISSUE TITLE
Edge module deployment issue - JSON error

### ISSUE THREAD

**Issue by davebanthorpe** [Azure/iot-edge#611]
OK so this issue only started happening this morning. Yesterday I had a fully operational edge runtime with 2 modules working perfectly. This morning one of the modules was not running and when I went into to edgeAgent logs I saw config errors - and I made no config changes over night.

So after trying to resolve unsuccessfully, cleared down the edge device (both locally and from Azure) and started from scratch.

Problem? Can't deploy ANY module other than edgeAgent or edgeHub. Even trying to deploy the example tempSensor module results in edge runtime reporting:

`400 - The deployment configuration is malformed or invalid`

and when you look at the logs of the edgeAgent, as soon as you try and submit a module deployment you see this. So has there been a bug introduced overnight into edge runtime????

```
2018-05-23 10:29:38.741 +00:00 [ERR] - Error refreshing edge agent configuration from twin.
Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigEmptyException: This device has an empty configuration for the edge agent. Please set a deployment manifest.
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 171
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<RefreshTwinAsync>d__20.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 124
2018-05-23 10:29:41.128 +00:00 [INF] - Updated reported properties
2018-05-23 10:31:48.726 +00:00 [ERR] - Error updating deployment config from edge agent desired properties.
Newtonsoft.Json.JsonSerializationException: Value cannot be null.
Parameter name: version
   at Microsoft.Azure.Devices.Edge.Agent.Core.Serde.TypeSpecificSerDe`1.Deserialize[TU](String json) in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/serde/TypeSpecificSerDe.cs:line 56
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 165
2018-05-23 10:31:48.751 +00:00 [ERR] - Edge agent failed to process desired properties update patch
Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigFormatException: Agent configuration format is invalid. ---> Newtonsoft.Json.JsonSerializationException: Value cannot be null.
Parameter name: version
   at Microsoft.Azure.Devices.Edge.Agent.Core.Serde.TypeSpecificSerDe`1.Deserialize[TU](String json) in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/serde/TypeSpecificSerDe.cs:line 56
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 165
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 177
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<ApplyPatchAsync>d__21.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 141
```

**Comment by carloshm** [comment]
Same issue:



    V2 issue

    OS version and architecture used: Raspberrypi Raspbian

    Version used: 1.0.0rc22

    V2 Docker version and container type: linux

**Comment by davebanthorpe** [comment]
Glad I'm not alone! I'll sit back and wait for MSFT to answer.

FYI have just re-verified on a brand new edge device (new windows, docker, python build).

**Comment by aribeironovaes** [comment]
Thanks for reporting! We are looking into it.

From the log message looks like something changed at the Agent Twin (service side) that made it stopped working, not at Edge runtime.

We will follow up ASAP.

Thanks

**Comment by jongio** [comment]
Please use the Az IoT CLI Extension as a workaround: https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-create-deployment-with-cli-iot-extension

**Comment by ChenchenC** [comment]
@jongio It does not work.

**Comment by darobs** [comment]
I just got word the UX team has rolled out a fix.  Please try the Azure Portal again.

From our UX team: "Users may encounter problems with javascript caching and users may need therefore clear cache if still encountering issue."

**Comment by davebanthorpe** [comment]
Update - UX Still not working, even tried from unused Edge browser so no cache issues to deal with.

CLI works fine.

**Comment by ChenchenC** [comment]
For my case, removing the UX Portal caching is helpful. It seems like the Portal can not support frequent module deployment operations.

**Comment by jongio** [comment]
@ChenchenC - LMK if you want to debug the CLI issue you had.  If so, let me know what you experienced. Error messages or  repro steps would be helpful.

**Comment by myagley** [comment]
This issue was resolved in the service and the portal has been verified to be working. Closing for now, but please reopen if the issue persists.
