### ISSUE TITLE
[V2] Issue deploying tempSensor module from tutorial

### ISSUE THREAD

**Issue by kieranmaltz** [Azure/iot-edge#615]
- **V1 or V2 issue** 
V2

- **OS version and architecture used:** <VERSION> 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
<Architecture> 
x86_64

- **Version used:** <VERSION> 
iotedgectl 1.0.0rc22

- **V2 Docker version and container type** <VERSION> <TYPE> 
Docker version 17.12.1-ce, build 7390fc6

# Description of the issue:
I have added the module using the standard image in the Azure Portal and submitted. 

I'm following the directions listed here: https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-simulate-device-Linux

# Console log of the issue:
2018-05-24 16:39:41.590 +00:00 [ERR] - Error updating deployment config from edge agent desired properties.
Newtonsoft.Json.JsonSerializationException: Value cannot be null.
Parameter name: version
   at Microsoft.Azure.Devices.Edge.Agent.Core.Serde.TypeSpecificSerDe`1.Deserialize[TU](String json) in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/serde/TypeSpecificSerDe.cs:line 56
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 165
2018-05-24 16:39:41.618 +00:00 [ERR] - Error refreshing edge agent configuration from twin.
Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigFormatException: Agent configuration format is invalid. ---> Newtonsoft.Json.JsonSerializationException: Value cannot be null.
Parameter name: version
   at Microsoft.Azure.Devices.Edge.Agent.Core.Serde.TypeSpecificSerDe`1.Deserialize[TU](String json) in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/serde/TypeSpecificSerDe.cs:line 56
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 165
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 177
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<RefreshTwinAsync>d__20.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 124

Here's the Device Twin json (clipped to most relevant info):
`{
  "deviceId": "simulated-device-one",
  "moduleId": "$edgeAgent",
  "etag": "AAAAAAAAAA0=",
  "deviceEtag": "MjgxMDY5OTEw",
  "status": "enabled",
  "statusUpdateTime": "0001-01-01T00:00:00",
  "connectionState": "Connected",
  "lastActivityTime": "0001-01-01T00:00:00",
  "cloudToDeviceMessageCount": 0,
  "authenticationType": "sas",
  "x509Thumbprint": {
    "primaryThumbprint": null,
    "secondaryThumbprint": null
  },
  "version": 48,
  "properties": {
    "desired": {
      "schemaVersion": "1.0",
      "runtime": {
        "type": "docker",
        "settings": {
          "minDockerVersion": "v1.25",
          "loggingOptions": ""
        }
      },
      "systemModules": {
        "edgeAgent": {
          "type": "docker",
          "settings": {
            "image": "microsoft/azureiotedge-agent:1.0-preview",
            "createOptions": "{}"
          }
        },
        "edgeHub": {
          "type": "docker",
          "status": "running",
          "restartPolicy": "always",
          "settings": {
            "image": "microsoft/azureiotedge-hub:1.0-preview",
            "createOptions": "{\"HostConfig\":{\"PortBindings\":{\"8883/tcp\":[{\"HostPort\":\"8883\"}],\"443/tcp\":[{\"HostPort\":\"443\"}]}}}"
          }
        }
      },
      "modules": {
        "tempSensor": {
          "type": "docker",
          "status": "running",
          "restartPolicy": "always",
          "settings": {
            "image": "microsoft/azureiotedge-simulated-temperature-sensor:1.0-preview",
            "createOptions": "{\"version\":1}"
          }
        }
      },
      "$metadata": { ... },
      "$version": 13
    },
    "reported": { ... }
  }
}`

**Comment by darobs** [comment]
Hello @kieranmaltz , this looks a lot like the same issue as was happening yesterday.  We believe the issue with deployments coming from Azure Portal have been resolved.

You may encounter problems with javascript caching and may need therefore clear cache if still encountering the issue.

Once our cache is clear, please submit the deployment again.

**Comment by darobs** [comment]
Marking this as a duplicate of #611, and closing, if you still are having this issue, please reopen.

**Comment by kieranmaltz** [comment]
Not sure how I missed that one. Thanks so much for the reply!
